# Data Preprocessing / Data Cleaning

In this notebook, I will expose two projects and not just one. That's because my intention is to demonstrate the different ways of preparing the various types of data, as this is a crucial step and usually the most time-consuming in a data science project.

In [124]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# First Project:

The first dataset is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013.

The second one is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD)

Finally, the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) is a rank of countries based on their journal contributions in the aforementioned area.

In this project I have to clean and join the three datasets: GDP, Energy, and ScimEn into a new dataset. Using only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).

In [45]:
x = pd.ExcelFile('Energy Indicators.xls')
energy = x.parse(skiprows=17,skip_footer=(38))
energy = energy[['Unnamed: 1','Petajoules','Gigajoules','%']]
energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,321,10,78.669280
1,Albania,102,35,100.000000
2,Algeria,1959,51,0.551010
3,American Samoa,...,...,0.641026
4,Andorra,9,121,88.695650
5,Angola,642,27,70.909090
6,Anguilla,2,136,0.000000
7,Antigua and Barbuda,8,84,0.000000
8,Argentina,3378,79,24.064520
9,Armenia,143,48,28.236060
10,Aruba,12,120,14.870690
11,Australia,5386,231,11.810810
12,Austria,1391,164,72.452820
13,Azerbaijan,567,60,6.384345
14,Bahamas,45,118,0.000000
15,Bahrain,574,425,0.000000
16,Bangladesh,1625,10,1.966329
17,Barbados,19,69,0.000000
18,Belarus,1142,120,0.463389
19,Belgium,2338,210,9.959739
20,Belize,13,39,64.690030
21,Benin,170,16,0.000000
22,Bermuda,6,88,0.000000
23,Bhutan,63,83,100.000000
24,Bolivia (Plurinational State of),336,32,31.477120
25,"Bonaire, Sint Eustatius and Saba",5,213,0.000000
26,Bosnia and Herzegovina,266,70,41.464670
27,Botswana,86,39,0.131406
28,Brazil,12149,59,69.648030
29,British Virgin Islands,2,85,0.000000
...,...,...,...,...
235,2,NaN,NaN,NaN
236,3,NaN,NaN,NaN
237,4,NaN,NaN,NaN
238,5,NaN,NaN,NaN
239,6,NaN,NaN,NaN
240,7,NaN,NaN,NaN
241,8,NaN,NaN,NaN
242,9,NaN,NaN,NaN
243,10,NaN,NaN,NaN
244,11,NaN,NaN,NaN
245,12,NaN,NaN,NaN
246,13,NaN,NaN,NaN
247,14,NaN,NaN,NaN
248,15,NaN,NaN,NaN
249,16,NaN,NaN,NaN
250,17,NaN,NaN,NaN
251,18,NaN,NaN,NaN
252,19,NaN,NaN,NaN
253,20,NaN,NaN,NaN
254,NaN,NaN,NaN,NaN
255,Definitions & Technical notes:,NaN,NaN,NaN
256,The data on energy supply and renewable electr...,NaN,NaN,NaN
257,Energy supply is defined as energy production ...,NaN,NaN,NaN
258,Electricity production refers to gross product...,NaN,NaN,NaN
259,Renewable electricity production (%) refers to...,NaN,NaN,NaN
260,… denotes no data available.,NaN,NaN,NaN
261,NaN,NaN,NaN,NaN
262,Data Quality:,NaN,NaN,NaN
263,The data are compiled primarily from the annua...,NaN,NaN,NaN
264,"For more information, visit http://unstats.un....",NaN,NaN,NaN

In [22]:
energy[['Energy Supply','Energy Supply per Capita','% Renewable']]=energy[['Energy Supply','Energy Supply per Capita','% Renewable']].replace('...',np.NaN).apply(pd.to_numeric)
energy['Energy Supply'] = 1000000*energy['Energy Supply']
energy['Country'] = energy['Country'].replace({'China, Hong Kong Special Administrative Region':'Hong Kong','United Kingdom of Great Britain and Northern Ireland':'United Kingdom','Republic of Korea':'South Korea','United States of America':'United States','Iran (Islamic Republic of)':'Iran'})
energy['Country'] = energy['Country'].str.replace(r" \(.*\)","")
energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+20,10.0,78.669280
1,Albania,1.020000e+20,35.0,100.000000
2,Algeria,1.959000e+21,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.000000e+18,121.0,88.695650
5,Angola,6.420000e+20,27.0,70.909090
6,Anguilla,2.000000e+18,136.0,0.000000
7,Antigua and Barbuda,8.000000e+18,84.0,0.000000
8,Argentina,3.378000e+21,79.0,24.064520
9,Armenia,1.430000e+20,48.0,28.236060
10,Aruba,1.200000e+19,120.0,14.870690
11,Australia,5.386000e+21,231.0,11.810810
12,Austria,1.391000e+21,164.0,72.452820
13,Azerbaijan,5.670000e+20,60.0,6.384345
14,Bahamas,4.500000e+19,118.0,0.000000
15,Bahrain,5.740000e+20,425.0,0.000000
16,Bangladesh,1.625000e+21,10.0,1.966329
17,Barbados,1.900000e+19,69.0,0.000000
18,Belarus,1.142000e+21,120.0,0.463389
19,Belgium,2.338000e+21,210.0,9.959739
20,Belize,1.300000e+19,39.0,64.690030
21,Benin,1.700000e+20,16.0,0.000000
22,Bermuda,6.000000e+18,88.0,0.000000
23,Bhutan,6.300000e+19,83.0,100.000000
24,Bolivia,3.360000e+20,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.000000e+18,213.0,0.000000
26,Bosnia and Herzegovina,2.660000e+20,70.0,41.464670
27,Botswana,8.600000e+19,39.0,0.131406
28,Brazil,1.214900e+22,59.0,69.648030
29,British Virgin Islands,2.000000e+18,85.0,0.000000
...,...,...,...,...
235,NaN,NaN,NaN,NaN
236,NaN,NaN,NaN,NaN
237,NaN,NaN,NaN,NaN
238,NaN,NaN,NaN,NaN
239,NaN,NaN,NaN,NaN
240,NaN,NaN,NaN,NaN
241,NaN,NaN,NaN,NaN
242,NaN,NaN,NaN,NaN
243,NaN,NaN,NaN,NaN
244,NaN,NaN,NaN,NaN
245,NaN,NaN,NaN,NaN
246,NaN,NaN,NaN,NaN
247,NaN,NaN,NaN,NaN
248,NaN,NaN,NaN,NaN
249,NaN,NaN,NaN,NaN
250,NaN,NaN,NaN,NaN
251,NaN,NaN,NaN,NaN
252,NaN,NaN,NaN,NaN
253,NaN,NaN,NaN,NaN
254,NaN,NaN,NaN,NaN
255,Definitions & Technical notes:,NaN,NaN,NaN
256,The data on energy supply and renewable electr...,NaN,NaN,NaN
257,Energy supply is defined as energy production ...,NaN,NaN,NaN
258,Electricity production refers to gross product...,NaN,NaN,NaN
259,Renewable electricity production measured at t...,NaN,NaN,NaN
260,… denotes no data available.,NaN,NaN,NaN
261,NaN,NaN,NaN,NaN
262,Data Quality:,NaN,NaN,NaN
263,The data are compiled primarily from the annua...,NaN,NaN,NaN
264,"For more information, visit http://unstats.un....",NaN,NaN,NaN

In [26]:
###########################   GDP   #########################

GDP = pd.read_csv('world_bank.csv', skiprows = 3)
GDP

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
0,Country Name,Country Code,Indicator Name,Indicator Code,1.960000e+03,1.961000e+03,1.962000e+03,1.963000e+03,1.964000e+03,1.965000e+03,...,2.006000e+03,2.007000e+03,2.008000e+03,2.009000e+03,2.010000e+03,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03
1,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
2,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
3,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
4,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
5,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
6,Arab World,ARB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
7,United Arab Emirates,ARE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
8,Argentina,ARG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.206739e+11,1.272239e+11,1.261399e+11,1.194442e+11,1.315442e+11,1.454477e+11,...,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
9,Armenia,ARM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
10,American Samoa,ASM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Antigua and Barbuda,ATG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
12,Australia,AUS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.983395e+11,2.032502e+11,2.059485e+11,2.187430e+11,2.340028e+11,2.479962e+11,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
13,Austria,AUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.223779e+10,9.734590e+10,9.992428e+10,1.040594e+11,1.104324e+11,1.142756e+11,...,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
14,Azerbaijan,AZE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
15,Burundi,BDI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.966083e+08,5.145977e+08,5.612365e+08,5.844459e+08,6.211084e+08,6.457492e+08,...,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
16,Belgium,BEL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.205638e+11,1.265660e+11,1.331626e+11,1.389573e+11,1.486241e+11,1.539161e+11,...,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
17,Benin,BEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.265426e+09,1.305177e+09,1.260456e+09,1.320076e+09,1.407871e+09,1.482402e+09,...,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
18,Burkina Faso,BFA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.120812e+09,1.166137e+09,1.237607e+09,1.221914e+09,1.249808e+09,1.296857e+09,...,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
19,Bangladesh,BGD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.786255e+10,1.894469e+10,1.997775e+10,1.988667e+10,2.206481e+10,2.241923e+10,...,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
20,Bulgaria,BGR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
21,Bahrain,BHR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
22,"Bahamas, The",BHS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.521892e+09,1.684234e+09,1.860270e+09,2.056046e+09,2.271963e+09,2.508828e+09,...,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
23,Bosnia and Herzegovina,BIH,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
24,Belarus,BLR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
25,Belize,BLZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.865406e+07,1.034805e+08,1.085434e+08,1.139233e+08,1.196193e+08,1.255172e+08,...,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
26,Bermuda,BMU,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.236025e+09,1.293871e+09,1.351707e+09,1.366170e+09,1.517951e+09,1.590206e+09,...,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
27,Bolivia,BOL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.818838e+09,4.919069e+09,5.193073e+09,5.526504e+09,5.791476e+09,6.117247e+09,...,1.644957e+10,1.720040e+10,1.825796e+10,1.887088e+10,1.964963e+10,2.067222e+10,2.173110e+10,2.320795e+10,2.447524e+10,2.544488e+10
28,Brazil,BRA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.466572e+11,2.720034e+11,2.861913e+11,2.886945e+11,2.987572e+11,3.078797e+11,...,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
29,Barbados,BRB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,4.490036e+09,4.490036e+09,4.498133e+09,4.542669e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,Middle East & North Africa (IDA & IBRD countries),TMN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,1.995513e+11,...,1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,1.381807e+12,1.394728e+12,1.416758e+12,NaN
236,Timor-Leste,TLS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
237,Tonga,TON,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
238,South Asia (IDA & IBRD),TSA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.840484e+11,1.916061e+11,1.979559e+11,2.086032e+11,2.246484e+11,2.223897e+11,...,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.448081e+11,2.484306e+11,2.629561e+11,2.795305e+11,2.945791e+11,3.123708e+11,...,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12
240,Trinidad and Tobago,TTO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.198187e+09,4.787490e+09,4.918785e+09,5.194463e+09,5.590826e+09,5.629618e+09,...,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
241,Tunisia,TUN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,5.059839e+09,...,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
242,Turkey,TUR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,8.362456e+10,8.459132e+10,8.930427e+10,9.740087e+10,1.027180e+11,1.056183e+11,...,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
243,Tuvalu,TUV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
244,Tanzania,TZA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10
245,Uganda,UGA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
246,Ukraine,UKR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
247,Upper middle income,UMC,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.456839e+12,1.477022e+12,1.541565e+12,1.631063e+12,1.764693e+12,1.884705e+12,...,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13
248,Uruguay,URY,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.389822e+10,1.424471e+10,1.402042e+10,1.404432e+10,1.438707e+10,1.453751e+10,...,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
249,United States,USA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.078071e+12,3.148867e+12,3.340948e+12,3.487949e+12,3.690250e+12,3.926426e+12,...,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
250,Uzbekistan,UZB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
251,St. Vincent and the Grenadines,VCT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.418778e+08,1.483010e+08,1.537796e+08,1.441448e+08,1.494345e+08,1.507569e+08,...,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08
252,"Venezuela, RB",VEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.015817e+11,1.048247e+11,1.137694e+11,1.182074e+11,1.313632e+11,1.368316e+11,...,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11
253,British Virgin Islands,VGB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Vietnam,VNM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11
256,Vanuatu,VUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
257,West Bank and Gaza,PSE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
258,World,WLD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.118678e+13,1.166806e+13,1.231357e+13,1.295118e+13,1.381212e+13,1.458038e+13,...,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
259,Samoa,WSM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08
260,"Yemen, Rep.",YEM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
261,South Africa,ZAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072507e+11,...,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
262,"Congo, Dem. Rep.",COD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
263,Zambia,ZMB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
264,Zimbabwe,ZWE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [27]:
head = GDP.iloc[0,:]
GDP.columns = head
GDP.drop(0, inplace = True)

GDP['Country Name'].replace('Korea, Rep.', 'South Korea', inplace = True)
GDP['Country Name'].replace('Iran, Islamic Rep.', 'Iran', inplace = True)
GDP['Country Name'].replace('Hong Kong SAR, China', 'Hong Kong', inplace = True)

GDP

,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
1,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
2,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
3,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
4,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
5,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
6,Arab World,ARB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
7,United Arab Emirates,ARE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
8,Argentina,ARG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.206739e+11,1.272239e+11,1.261399e+11,1.194442e+11,1.315442e+11,1.454477e+11,...,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
9,Armenia,ARM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
10,American Samoa,ASM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Antigua and Barbuda,ATG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
12,Australia,AUS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.983395e+11,2.032502e+11,2.059485e+11,2.187430e+11,2.340028e+11,2.479962e+11,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
13,Austria,AUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.223779e+10,9.734590e+10,9.992428e+10,1.040594e+11,1.104324e+11,1.142756e+11,...,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
14,Azerbaijan,AZE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
15,Burundi,BDI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.966083e+08,5.145977e+08,5.612365e+08,5.844459e+08,6.211084e+08,6.457492e+08,...,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
16,Belgium,BEL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.205638e+11,1.265660e+11,1.331626e+11,1.389573e+11,1.486241e+11,1.539161e+11,...,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
17,Benin,BEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.265426e+09,1.305177e+09,1.260456e+09,1.320076e+09,1.407871e+09,1.482402e+09,...,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
18,Burkina Faso,BFA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.120812e+09,1.166137e+09,1.237607e+09,1.221914e+09,1.249808e+09,1.296857e+09,...,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
19,Bangladesh,BGD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.786255e+10,1.894469e+10,1.997775e+10,1.988667e+10,2.206481e+10,2.241923e+10,...,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
20,Bulgaria,BGR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
21,Bahrain,BHR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
22,"Bahamas, The",BHS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.521892e+09,1.684234e+09,1.860270e+09,2.056046e+09,2.271963e+09,2.508828e+09,...,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
23,Bosnia and Herzegovina,BIH,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
24,Belarus,BLR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
25,Belize,BLZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.865406e+07,1.034805e+08,1.085434e+08,1.139233e+08,1.196193e+08,1.255172e+08,...,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
26,Bermuda,BMU,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.236025e+09,1.293871e+09,1.351707e+09,1.366170e+09,1.517951e+09,1.590206e+09,...,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
27,Bolivia,BOL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.818838e+09,4.919069e+09,5.193073e+09,5.526504e+09,5.791476e+09,6.117247e+09,...,1.644957e+10,1.720040e+10,1.825796e+10,1.887088e+10,1.964963e+10,2.067222e+10,2.173110e+10,2.320795e+10,2.447524e+10,2.544488e+10
28,Brazil,BRA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.466572e+11,2.720034e+11,2.861913e+11,2.886945e+11,2.987572e+11,3.078797e+11,...,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
29,Barbados,BRB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,4.490036e+09,4.490036e+09,4.498133e+09,4.542669e+09
30,Brunei Darussalam,BRN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249730e+10,1.251661e+10,1.227383e+10,1.205725e+10,1.237062e+10,1.279491e+10,1.291625e+10,1.268996e+10,1.239301e+10,1.233105e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,Middle East & North Africa (IDA & IBRD countries),TMN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,1.995513e+11,...,1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,1.381807e+12,1.394728e+12,1.416758e+12,NaN
236,Timor-Leste,TLS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
237,Tonga,TON,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
238,South Asia (IDA & IBRD),TSA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.840484e+11,1.916061e+11,1.979559e+11,2.086032e+11,2.246484e+11,2.223897e+11,...,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.448081e+11,2.484306e+11,2.629561e+11,2.795305e+11,2.945791e+11,3.123708e+11,...,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12
240,Trinidad and Tobago,TTO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.198187e+09,4.787490e+09,4.918785e+09,5.194463e+09,5.590826e+09,5.629618e+09,...,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
241,Tunisia,TUN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,5.059839e+09,...,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
242,Turkey,TUR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,8.362456e+10,8.459132e+10,8.930427e+10,9.740087e+10,1.027180e+11,1.056183e+11,...,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
243,Tuvalu,TUV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
244,Tanzania,TZA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10
245,Uganda,UGA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
246,Ukraine,UKR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
247,Upper middle income,UMC,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.456839e+12,1.477022e+12,1.541565e+12,1.631063e+12,1.764693e+12,1.884705e+12,...,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13
248,Uruguay,URY,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.389822e+10,1.424471e+10,1.402042e+10,1.404432e+10,1.438707e+10,1.453751e+10,...,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
249,United States,USA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.078071e+12,3.148867e+12,3.340948e+12,3.487949e+12,3.690250e+12,3.926426e+12,...,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
250,Uzbekistan,UZB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
251,St. Vincent and the Grenadines,VCT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.418778e+08,1.483010e+08,1.537796e+08,1.441448e+08,1.494345e+08,1.507569e+08,...,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08
252,"Venezuela, RB",VEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.015817e+11,1.048247e+11,1.137694e+11,1.182074e+11,1.313632e+11,1.368316e+11,...,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11
253,British Virgin Islands,VGB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Vietnam,VNM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11
256,Vanuatu,VUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
257,West Bank and Gaza,PSE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
258,World,WLD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.118678e+13,1.166806e+13,1.231357e+13,1.295118e+13,1.381212e+13,1.458038e+13,...,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
259,Samoa,WSM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08
260,"Yemen, Rep.",YEM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
261,South Africa,ZAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072507e+11,...,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
262,"Congo, Dem. Rep.",COD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
263,Zambia,ZMB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
264,Zimbabwe,ZWE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [28]:
########################   ScimEn   #########################

ScimEn = pd.read_excel('scimagojr-3.xlsx')
ScimEn

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57
5,6,Canada,17899,17620,215003,40930,12.01,149
6,7,Germany,17027,16831,140566,27426,8.26,126
7,8,India,15005,14841,128763,37209,8.58,115
8,9,France,13153,12973,130632,28601,9.93,114
9,10,South Korea,11983,11923,114675,22595,9.57,104
10,11,Italy,10964,10794,111850,26661,10.20,106
11,12,Spain,9428,9330,123336,23964,13.08,115
12,13,Iran,8896,8819,57470,19125,6.46,72
13,14,Australia,8831,8725,90765,15606,10.28,107
14,15,Brazil,8668,8596,60702,14396,7.00,86
15,16,Taiwan,6468,6441,86099,14768,13.31,102
16,17,Turkey,5879,5827,91857,23165,15.62,104
17,18,Norway,5675,5634,32693,6024,5.76,74
18,19,Netherlands,5170,5105,48351,6067,9.35,85
19,20,Sweden,4565,4494,57889,9632,12.68,95
20,21,Malaysia,3914,3881,25545,6597,6.53,62
21,22,Switzerland,3636,3599,38962,6186,10.72,81
22,23,Denmark,3531,3494,37254,6191,10.55,85
23,24,Mexico,3249,3214,21524,4145,6.62,57
24,25,Poland,3123,3102,24852,5395,7.96,55
25,26,Saudi Arabia,2979,2930,21208,2469,7.12,61
26,27,Greece,2866,2835,41662,6226,14.54,82
27,28,Egypt,2789,2752,19123,2778,6.86,55
28,29,Belgium,2697,2642,23720,3300,8.79,63
29,30,Singapore,2488,2443,36098,3700,14.51,81
...,...,...,...,...,...,...,...,...
161,162,Greenland,3,3,49,0,16.33,2
162,163,Afghanistan,3,3,0,0,0.00,0
163,164,Cape Verde,3,3,5,0,1.67,1
164,165,French Guiana,3,3,1,1,0.33,1
165,166,Samoa,3,3,13,1,4.33,1
166,167,Cayman Islands,2,2,2,0,1.00,1
167,168,Andorra,2,2,13,0,6.50,1
168,169,Antigua and Barbuda,2,2,0,0,0.00,0
169,170,Haïti,2,2,4,1,2.00,1
170,171,Nauru,2,2,0,0,0.00,0
171,172,Seychelles,2,2,7,2,3.50,1
172,173,Mali,2,2,0,0,0.00,0
173,174,Bermuda,2,2,12,0,6.00,1
174,175,Chad,2,2,0,0,0.00,0
175,176,Burundi,2,2,23,0,11.50,1
176,177,Liberia,1,1,1,0,1.00,1
177,178,Togo,1,1,0,0,0.00,0
178,179,British Indian Ocean Territory,1,1,37,0,37.00,1
179,180,American Samoa,1,1,0,0,0.00,0
180,181,Saint Helena,1,1,1,0,1.00,1
181,182,Gibraltar,1,1,0,0,0.00,0
182,183,Maldives,1,1,1,0,1.00,1
183,184,Gambia,1,1,0,0,0.00,0
184,185,Belize,1,1,6,0,6.00,1
185,186,Palau,1,1,0,0,0.00,0
186,187,Guyana,1,1,0,0,0.00,0
187,188,Christmas Island,1,1,0,0,0.00,0
188,189,Reunion,1,1,2,1,2.00,1
189,190,Saint Lucia,1,1,0,0,0.00,0
190,191,Mauritania,1,1,1,0,1.00,1

In [35]:
#######################   Merging  ##########################

ne = pd.merge(ScimEn,energy, how='inner', left_on='Country', right_on='Country')
new = pd.merge(ne, GDP, how = 'inner', left_on = 'Country',right_on = 'Country Name')
new.set_index('Country', inplace = True)

cols = ['Country Name','Country Code','Indicator Name','Indicator Code',1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,
        1966.0,1967.0, 1968.0,1969.0,1970.0, 1971.0,1972.0, 1973.0,1974.0, 1975.0,1976.0, 1977.0,1978.0, 1979.0,
        1980.0, 1981.0,1982.0, 1983.0,1984.0, 1985.0,1986.0, 1987.0,1988.0, 1989.0,1990.0, 1991.0,1992.0, 1993.0,
        1994.0, 1995.0,1996.0, 1997.0,1998.0, 1999.0,2000.0, 2001.0,2002.0, 2003.0,2004.0, 2005.0,]

new.drop(cols, axis = 1, inplace = True)
new = new.iloc[0:15,:]

new.rename(columns=({2006.0:'2006',2007.0:'2007',2008.0:'2008',2009.0:'2009',2010.0:'2010',
                     2011.0:'2011',2012.0:'2012',2013.0:'2013',2014.0:'2014',2015.0:'2015'}), inplace = True)

new

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+23,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+22,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+22,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+21,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+22,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+22,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+22,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+22,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+22,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+22,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+21,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+21,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+21,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+21,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+22,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

**Now, with the data already processed and with this new data set, we can answer questions like: increasing GDP in the last 10 years, the energy supply per capita, the country with the maximum % of renewable energy and many others**

# Second Project:

* Iterate a .txt file from a list of [university towns in the United States](https://en.wikipedia.org/wiki/List_of_college_towns#College_towns_in_the_United_States).

In [54]:
univ =  open('university_towns.txt','r')

sta = ('Alabama\n','Alaska\n','Arizona\n','Arkansas\n','California\n','Colorado\n','Connecticut\n','Delaware\n','Florida\n','Georgia\n','Hawaii\n',
       'Idaho\n','Illinois\n','Indiana\n','Iowa\n','Kansas\n','Kentucky\n','Louisiana\n','Maine\n','Maryland\n','Massachusetts\n','Michigan\n',
       'Minnesota\n','Mississippi\n','Missouri\n','Montana\n','Nebraska\n','Nevada\n','New Hampshire\n','New Jersey\n',
       'New Mexico\n','New York\n','North Carolina\n','North Dakota\n','Ohio\n','Oklahoma\n','Oregon\n','Pennsylvania\n','Rhode Island\n',
       'South Carolina\n','South Dakota\n','Tennessee\n','Texas\n','Utah\n','Vermont\n','Virginia\n','Washington\n','West Virginia\n',
       'Wisconsin\n','Wyoming\n')


estados = []
uni = []

for x in univ:
    uni.append(x)
    if x.startswith(sta): 
        estados.append(x)
uni

['Alabama\n',
 'Auburn (Auburn University, Edward Via College of Osteopathic Medicine)[6]\n',
 'Birmingham (University of Alabama at Birmingham, Birmingham School of Law, Birmingham Southern College, Cumberland School of Law, Miles Law School)[7]\n',
 'Dothan (Fortis College, Troy University Dothan Campus, Alabama College of Osteopathic Medicine)\n',
 'Florence (University of North Alabama)\n',
 'Homewood (Samford University)\n',
 'Huntsville (University of Alabama, Huntsville)\n',
 'Jacksonville (Jacksonville State University)[8]\n',
 'Livingston (University of West Alabama)[8]\n',
 'Mobile (University of South Alabama)[7]\n',
 'Montevallo (University of Montevallo, Faulkner University)[8]\n',
 'Montgomery (Alabama State University, Huntingdon College, Auburn University at Montgomery, H. Councill Trenholm State Technical College, Faulkner University)\n',
 'Troy (Troy University)[8][9]\n',
 'Tuscaloosa (University of Alabama, Stillman College, Shelton State)[10][11]\n',
 'Tuskegee (Tuskegee University)[12]\n',
 'Alaska\n',
 'Anchorage[13] (University of Alaska Anchorage)\n',
 'Fairbanks (University of Alaska Fairbanks)[8]\n',
 'Juneau (University of Alaska Southeast)\n',
 'Ketchikan (University of Alaska Southeast-extended campus)\n',
 'Sitka (University of Alaska Southeast-extended campus)\n',
 'Arizona\n',
 'Chandler[13] (Western International University, University of Phoenix, International Baptist College, Ottawa University (adult education programs), Chandler University)\n',
 'Flagstaff (Northern Arizona University)[14]\n',
 'Gilbert[13]\n',
 'Glendale[13] (Thunderbird School of Global Management at ASU, Midwestern University Glendale campus)\n',
 'Lake Havasu City (ASU Colleges at Lake Havasu City, Northern Arizona University extended campus)\n',
 'Mesa[13] (Arizona State University Polytechnic campus, Benedictine University branch campus, Upper Iowa University branch campus, A.T. Still University School of Osteopathic Medicine in Arizona)\n',
 'Peoria[13] (Trine University branch campus)\n',
 'Phoenix[13] (Arizona State University, University of Phoenix, University of Arizona College of Medicine, small satellite campus for Northern Arizona University, Grand Canyon University, Arizona Summit Law School, Arizona Christian University)\n',
 'Prescott (Embryâ€“Riddle Aeronautical University, Yavapai College, Prescott College, Northern Arizona University, Old Dominion University)\n',
 'Scottsdale[13] (University of Phoenix)\n',
 'Tempe (Arizona State University, University of Phoenix, Brookline College, Bryan University)[9]\n',
 'Tucson (University of Arizona, Tucson College, Brown Mackie College, Brookline College, University of Phoenix, The Art Institute of Tucson, Prescott College branch campus, Northern Arizona University branch campus, The Art Center Design College, Wayland Baptist University)\n',
 'Arkansas\n',
 'Arkadelphia (Henderson State University, Ouachita Baptist University)[8]\n',
 'Conway (Central Baptist College, Hendrix College, University of Central Arkansas)[8]\n',
 'Fayetteville (University of Arkansas)[15]\n',
 'Fort Smith (University of Arkansas at Fort Smith, Webster University satellite campus, John Brown University satellite campus, Arkansas College of Osteopathic Medicine)\n',
 'Jonesboro (Arkansas State University)[16]\n',
 'Little Rock[13] (University of Arkansas at Little Rock, University of Arkansas for Medical Sciences, Philander Smith College, Arkansas Baptist College)\n',
 'Magnolia (Southern Arkansas University)[8]\n',
 'Monticello (University of Arkansas at Monticello)[8]\n',
 'Russellville (Arkansas Tech University)[8]\n',
 'Searcy (Harding University)[12]\n',
 'California\n',
 'Acton (Larry H. Layton School of Law)\n',
 "Alhambra (Platt College, Alhambra branch of Everest College, Los Angeles Campus of Alliant International University, University of Southern California's Health Sciences Alhambra campus)\n",
 'Anaheim (Anaheim University, California Institute of Technology (SCIT), Bristol University)\n',
 'Angwin (Pacific Union College)[8]\n',
 'Antioch[13]\n',
 'Arcata (Humboldt State University)[12]\n',
 'Arden-Arcade[13]\n',
 'Azusa\n',
 'Bakersfield[13] (California State University, Bakersfield; University of LaVerne, Fresno Pacific University, and Point Loma Nazarene University branch campuses, San Joaquin Valley College, Santa Barbara Business College)\n',
 'Berkeley (University of California, Berkeley)[12]\n',
 'Burbank (Woodbury University)\n',
 'Camarillo (California State University Channel Islands)\n',
 'Carson (California State University, Dominguez Hills)\n',
 'Cerritos (Cerritos College, Fremont College, Irvine University College of Law)\n',
 'Chico (California State University, Chico, Cal Northern School of Law)[8]\n',
 'Chino Hills (Biola University (Satellite Campus))\n',
 'Chula Vista (Southwestern College)\n',
 'Claremont (Claremont McKenna College, Pomona College, Harvey Mudd College, Scripps College, Pitzer College, Keck Graduate Institute, Claremont Graduate University)[12]\n',
 'Compton (El Camino College)\n',
 'Corona\n',
 'Costa Mesa (Orange Coast College, Vanguard University, Whittier Law School (a satellite of Whittier College) and National University satellite campus)\n',
 'Cotati (California State University, Sonoma)[8]\n',
 'Davis (University of California, Davis)[6]\n',
 'Downey\n',
 'East Los Angeles\n',
 'El Cajon (Cuyamaca College, Grossmont College, San Diego Christian College)\n',
 'Elk Grove[13] (California Northstate University College of Pharmacy)\n',
 'Escondido[citation needed]\n',
 'Fairfield[13] (Solano Community College, satellite campuses of University of Phoenix, Brandman University, InterCoast Colleges, and Embry Riddle Aeronautical University (at Travis AFB))\n',
 'Fresno[13] (Alliant International University, California Christian College, California State University, Fresno, Fresno Pacific University, Kaplan College Fresno campus, National University Fresno campus, University of California, San Francisco â€“ Fresno Medical Education Program, University of California, Merced, University of Phoenix)[citation needed]\n',
 'Fullerton (California State University, Fullerton, Western State College of Law at Argosy University, Hope International University, Marshall B. Ketchum University, Fullerton College)\n',
 'Garden Grove\n',
 'Glendale (Glendale University College of Law)\n',
 'Hawthorne (Los Angeles Southwest College, El Camino College)\n',
 'Huntington Beach (Golden West College)\n',
 'Indio (California Desert Trial Academy College of Law)\n',
 'Inglewood (University of West Los Angeles)\n',
 'Irvine (University of California, Irvine, Western State College of Law at Argosy University)\n',
 'Isla Vista (University of California, Santa Barbara)[8]\n',
 'Lancaster (University of Antelope Valley, Antelope Valley College, satellite campus of California State University, Bakersfield, Charter College)\n',
 'La Mesa (McMillan Academy of Law)\n',
 'La Verne (University of La Verne)\n',
 'Loma Linda (Loma Linda University)\n',
 'Long Beach (California State University, Long Beach, Pacific Coast University School of Law)[9]\n',
 'Los Angeles (California State University, Los Angeles, California State University, Northridge, University of California, Los Angeles)[13]\n',
 'Chatsworth (University of West Los Angeles)\n',
 'Downtown Los Angeles (Peoples College of Law)\n',
 'Mid-Wilshire (Southwestern University School of Law)\n',
 'Pico-Union (Loyola Law School)\n',
 'University Park (University of Southern California)\n',
 'Westchester (Loyola Marymount University)\n',
 'Malibu (Pepperdine University)[9]\n',
 'Merced (University of California, Merced)\n',
 'Moreno Valley (Chapman University, Moreno Valley College)\n',
 'Murrieta[13] (University of Phoenix learning center, Azusa Pacific University satellite campus)\n',
 'Norwalk (Cerritos College)\n',
 'Oceanside (Mira Costa College)\n',
 'Ontario (University of La Verne College of Law)\n',
 'Orange (Chapman University, Pacific West College of Law)\n',
 'Oxnard[13] (Oxnard College; California Lutheran University, California State University, Northridge, ITT, University of Phoenix, University of California, Santa Barbara, National University and Azusa Pacific University have satellite campuses )\n',
 'Palmdale (Chapman University satellite campus, University of Antelope Valley, University of La Verne satellite campus)\n',
 'Palo Alto (Stanford University)\n',
 'Pasadena (California Institute of Technology, Pasadena City College, Pacific Oaks College)[13]\n',
 'Pleasant Hill (John F. Kennedy University)[citation needed]\n',
 'Pomona (Cal Poly Pomona, Western University of Health Sciences)[17][18][19] and formerly Pomona College\n',
 'Rancho Cucamonga (Chaffey College and satellite campuses of the University of La Verne, Cambridge College, University of Redlands, Everest College, and University of Phoenix)\n',
 'Redding[13] (Simpson University, National University, Shasta Bible College and Graduate School, California State University, Chico branch campus)\n',
 'Redlands (University of Redlands)\n',
 'Riverside (University of California, Riverside, California Baptist University, La Sierra University, California Southern Law School)\n',
 'Rocklin (Sierra College, William Jessup University)\n',
 'Roseville[13] (Brandman University extension campus )\n',
 'Sacramento :\n',
 'East Sacramento (California State University, Sacramento, Lincoln Law School of Sacramento)\n',
 'Oak Park (University of the Pacific, McGeorge School of Law)\n',
 'Salinas[13] (Hartnell College)\n',
 'San Bernardino (California State University, San Bernardino, American Sports University)\n',
 'San Diego (University of California, San Diego, San Diego State University, California Western School of Law, Thomas Jefferson School of Law, University of San Diego, Western Sierra Law School)\n',
 'San Francisco (University of California, San Francisco, San Francisco State University, California State University, University of San Francisco, Golden Gate University, University of the Pacific Arthur A. Dugoni School of Dentistry, San Francisco Law School, University of California, Hastings College of the Law)[13]\n',
 'San Jose[13] (San Jose State University, Lincoln Law School of San Jose)\n',
 'San Luis Obispo (California Polytechnic State University, University of San Luis Obispo School of Law)[8]\n',
 'San Marcos (California State University San Marcos, University of St. Augustine for Health Sciences)\n',
 'Santa Ana (Trinity Law School)\n',
 'Santa Barbara (Fielding Graduate University, Santa Barbara City College, University of California, Santa Barbara, Westmont College, Santa Barbara College of Law, Southern California Institute of Law)[8]\n',
 'Santa Clara[13] (Santa Clara University)\n',
 "Santa Clarita (California Institute of the Arts, The Master's College, College of the Canyons)\n",
 'Santa Cruz (University of California, Santa Cruz)[8]\n',
 'Santa Monica (Santa Monica College)\n',
 'Seaside (Monterey College of Law)\n',
 'Simi Valley[citation needed]\n',
 'Stanford (Stanford University)[13]\n',
 'Stockton[13] (University of the Pacific, Humphreys College-main campus)\n',
 'Sunnyvale[13]\n',
 'Temecula\n',
 'Torrance[citation needed]\n',
 'Thousand Oaks (California Lutheran University)\n',
 'Turlock (California State University, Stanislaus)\n',
 'Vallejo[13] (Touro University California College of Osteopathic Medicine)[citation needed]\n',
 'Ventura[13] (Santa Barbara College of Law, Southern California Institute of Law)\n',
 'Victorville\n',
 'Visalia[13] (Fresno State branch campus, Chapman University branch campus, Fresno Pacific University branch campus, Brandman University branch campus, San Joaquin Valley College)\n',
 'Westminster\n',
 'West Covina\n',
 'Whittier (Whittier College, Rio Hondo College)\n',
 'Colorado\n',
 'Alamosa (Adams State College)[8]\n',
 'Aurora (Columbia Collegeâ€“Aurora, Ecotech Institute, University of Colorado Denver at the Anschutz Medical Campus, Colorado Community College System)\n',
 'Boulder (University of Colorado at Boulder, Naropa University)[20]\n',
 'Colorado Springs (United States Air Force Academy, University of Colorado Colorado Springs, Colorado College, Colorado Technical University)\n',
 'Denver (University of Colorado Denver, Metropolitan State University of Denver, University of Denver, Johnson & Wales University, Regis University)[13]\n',
 'Durango (Fort Lewis College)[8]\n',
 'Fort Collins (Colorado State University)[21]\n',
 'Golden (Colorado School of Mines)\n',
 'Grand Junction (Colorado Mesa University)\n',
 'Greeley (University of Northern Colorado)\n',
 'Gunnison (Western State College)[8]\n',
 'Lakewood (Colorado Christian University)\n',
 'Pueblo (Colorado State Universityâ€“Pueblo)\n',
 'Connecticut\n',
 "Bridgeport (St. Vincent's College, University of Bridgeport)\n",
 'Danbury (Western Connecticut State University)\n',
 'East Hartford (Goodwin College)\n',
 'Fairfield (Fairfield University, Sacred Heart University)[22]\n',
 'Farmington (UConn Health)\n',
 'Hamden (Quinnipiac University)\n',
 'Hartford (Rensselaer at Hartford, Trinity College, University of Connecticut School of Law)\n',
 'Middletown (Wesleyan University)\n',
 'New Britain (Central Connecticut State University)\n',
 'New Haven (Yale University, University of New Haven, Southern Connecticut State University, Albertus Magnus College, Quinnipiac University)[23]\n',
 'New London (Connecticut College, US Coast Guard Academy, Mitchell College)[8]\n',
 'Southington (New England Baptist College)\n',
 'Stamford (University of Connecticut, University of Bridgeport and Sacred Heart University branch campuses)\n',
 'Storrs (University of Connecticut)[8]\n',
 'Waterbury (Post University, University of Bridgeport (Regional Campus), University of Connecticut (Regional Campus / Downtown Waterbury), Western Connecticut State University (Regional Campus))\n',
 'Willimantic (Eastern Connecticut State University)[8]\n',
 'West Hartford (University of Hartford, University of Saint Joseph, University of Connecticut Greater Hartford campus)\n',
 'West Haven (University of New Haven)[22]\n',
 'Delaware\n',
 'Dover (Delaware State University, Wesley College)[6]\n',
 'Newark (University of Delaware)[6]\n',
 'New Castle (Wilmington University)\n',
 'Wilmington (Delaware College of Art & Design, Drexel University â€“ Wilmington Campus, Springfield College â€“ Wilmington Campus, Widener Universityâ€“Delaware Campus)\n',
 'District of Columbia\n',
 "Washington, D.C. (Georgetown University, Howard University, American University, the Catholic University of America, Gallaudet University, George Washington University, Johns Hopkins University School of Advanced International Studies, Trinity Washington University, University of the District of Columbia, Graduate School USA, St. Paul's College, Institute of World Politics)[13]\n",
 'Florida\n',
 'Ave Maria (Ave Maria University)\n',
 'Boca Raton (Florida Atlantic University)\n',
 'Bradenton (Lake Erie College of Osteopathic Medicine branch campus)\n',
 'Brandon\n',
 'Cape Coral (Florida Gulf Coast University satellite facility)\n',
 'Coral Gables (University of Miami)\n',
 'Coral Springs (Barry University, Nova Southeastern University and Broward College)\n',
 'Davie (Nova Southeastern University)\n',
 'Daytona Beach (Embryâ€“Riddle Aeronautical University)\n',
 'DeLand (Stetson University)[12]\n',
 'Estero (Florida Gulf Coast University)\n',
 'Fort Lauderdale (Broward College BC (Willis Holcombe Downtown Center), City College, Florida Atlantic University FAU (satellite campus), Florida International University FIU (satellite campus), Keiser University, Nova Southeastern University NSU (satellite campus), The Art Institute of Fort Lauderdale, University of Phoenix (Cypress Creek Learning Center), Jersey College)\n',
 'Fort Myers (Florida Gulf Coast University)\n',
 'Gainesville (University of Florida, Santa Fe College)[9]\n',
 'Gulfport (Stetson University College of Law, St. Petersburg College, University of South Florida branch campus)\n',
 'Hialeah (College of Business and Technology, Florida National University)\n',
 'Hollywood\n',
 'Jacksonville (University of North Florida, Jacksonville University, Florida State College at Jacksonville, University of Florida second campus, Florida Coastal School of Law and Jones College)\n',
 'Kendall (Keiser College, Miami-Dade College (Kendall Campus), Nova Southeastern University (Miami Student Educational Center), College of Business and Technology (Kendall Campus))\n',
 'Lakeland (Florida Polytechnic University)\n',
 'Miami (Florida International University)\n',
 'Miami Gardens (St. Thomas University, Florida Memorial University, CBT College)\n',
 'Miramar (Broward College (Miramar Town Center), Broward College (Miramar West Center), Florida International University (FIU) (Miramar West Center), Nova Southeastern University (Miramar Campus))\n',
 'Panama City (Gulf Coast State College)[9]\n',
 'Pembroke Pines (The Broward-Pines Center regional campus of Barry University, The Broward-Pines Center regional campus of Broward College,The Broward-Pines Center regional campus of Florida International University,The South regional campus of Broward College, Keiser University Pembroke Pines Campus)\n',
 'Port St. Lucie (Indian River State College, Barry University, and Keiser University)\n',
 'Orlando (University of Central Florida)\n',
 'Sarasota (New College of Florida, Ringling College of Art and Design, State College of Florida, Manatee-Sarasota, University of South Florida Sarasota-Manatee)\n',
 'St. Augustine (Flagler College)[9]\n',
 'St. Leo (St. Leo University)\n',
 'St. Petersburg (University of South Florida St. Petersburg, Eckerd College, St. Petersburg College)\n',
 'Sunrise\n',
 'Tallahassee (Florida State University, Florida A&M University)\n',
 'Tampa (University of South Florida)\n',
 'West Palm Beach (Palm Beach Atlantic University, Keiser University)\n',
 'Georgia\n',
 'Albany (Albany State University)\n',
 'Alpharetta (Georgia State University, Gwinnett Technical College, Reinhardt University)\n',
 'Athens (University of Georgia, Athens Technical College)[24]\n',
 'Atlanta (Georgia Tech, Clark Atlanta University, Morehouse College, Spelman College, Art Institute of Atlanta, Mercer University):[8]\n',
 'Downtown (Georgia State University)\n',
 'Druid Hills (Emory University)\n',
 'Midtown (John Marshall Law School)\n',
 'Augusta (Augusta Technical College, Augusta University, Paine College, East Georgia State College)\n',
 'Blue Ridge (University of North Georgia)\n',
 'Brunswick (College of Coastal Georgia)[9]\n',
 'Carrollton (University of West Georgia)[8]\n',
 'Columbus (Columbus State University, Columbus Technical College)\n',
 'Cumming (University of North Georgia)\n',
 'Dahlonega (University of North Georgia)\n',
 'Demorest (Piedmont College)[8]\n',
 'Fort Valley (Fort Valley State University)[8]\n',
 'Gainesville (University of North Georgia Gainesville Campus, Brenau University)\n',
 'Glennville (Southeastern Technical College)\n',
 'Kennesaw (Kennesaw State University)\n',
 'Lawrenceville (Georgia Gwinnett College, Gwinnett Technical College)\n',
 'Madison (Georgia Military College Madison Campus)\n',
 'Macon (Mercer University, Middle Georgia State University, Wesleyan College, Central Georgia Technical College, Fort Valley State University - satellite campus, Georgia College & State University - satellite campus)\n',
 'Milledgeville (Georgia College & State University, Georgia Military College)[8]\n',
 'Monroe\n',
 'Mount Vernon (Brewton-Parker College)[8]\n',
 'Oxford (Oxford College)\n',
 'Rome (Berry College, Shorter University)\n',
 'Savannah (Armstrong Atlantic State University, Savannah State University, Savannah College of Art and Design, Savannah Law School)[9]\n',
 'Statesboro (Georgia Southern University, East Georgia State College)[12]\n',

This above is the Raw Data. The chellange is to create a dataframe of the towns and the states they are in, like:

DataFrame([ ["Michigan", "Ann Arbor"], ["Michigan", "Yipsilanti"]])

In [55]:
df = pd.DataFrame(uni)
df.columns = ['StateRegion']
estados = pd.DataFrame(estados)
estados.columns = ['StateRegion']
df

                                            StateRegion
0                                             Alabama\n
1     Auburn (Auburn University, Edward Via College ...
2     Birmingham (University of Alabama at Birmingha...
3     Dothan (Fortis College, Troy University Dothan...
4              Florence (University of North Alabama)\n
5                       Homewood (Samford University)\n
6      Huntsville (University of Alabama, Huntsville)\n
7     Jacksonville (Jacksonville State University)[8]\n
8          Livingston (University of West Alabama)[8]\n
9             Mobile (University of South Alabama)[7]\n
10    Montevallo (University of Montevallo, Faulkner...
11    Montgomery (Alabama State University, Huntingd...
12                       Troy (Troy University)[8][9]\n
13    Tuscaloosa (University of Alabama, Stillman Co...
14                 Tuskegee (Tuskegee University)[12]\n
15                                             Alaska\n
16     Anchorage[13] (University of Alaska Anchorage)\n
17      Fairbanks (University of Alaska Fairbanks)[8]\n
18            Juneau (University of Alaska Southeast)\n
19    Ketchikan (University of Alaska Southeast-exte...
20    Sitka (University of Alaska Southeast-extended...
21                                            Arizona\n
22    Chandler[13] (Western International University...
23        Flagstaff (Northern Arizona University)[14]\n
24                                        Gilbert[13]\n
25    Glendale[13] (Thunderbird School of Global Man...
26    Lake Havasu City (ASU Colleges at Lake Havasu ...
27    Mesa[13] (Arizona State University Polytechnic...
28        Peoria[13] (Trine University branch campus)\n
29    Phoenix[13] (Arizona State University, Univers...
...                                                 ...
975   Vancouver (Washington State University Vancouv...
976                                     West Virginia\n
977                    Athens (Concord University)[8]\n
978   Beckley (West Virginia University Institute of...
979    Buckhannon (West Virginia Wesleyan College)[8]\n
980                   Elkins (Davis & Elkins College)\n
981           Fairmont (Fairmont State University)[8]\n
982            Glenville (Glenville State College)[8]\n
983        Institute (West Virginia State University)\n
984   Lewisburg (West Virginia School of Osteopathic...
985          Morgantown (West Virginia University)[8]\n
986            Shepherdstown (Shepherd University)[8]\n
987         West Liberty (West Liberty University)[8]\n
988                                         Wisconsin\n
989                    Appleton (Lawrence University)\n
990   Eau Claire (University of Wisconsinâ€“Eau Clai...
991     Green Bay (University of Wisconsin-Green Bay)\n
992   Kenosha (University of Wisconsin-Parkside, Car...
993   La Crosse (University of Wisconsinâ€“La Crosse...
994    Madison (University of Wisconsinâ€“Madison)[8]\n
995    Menomonie (University of Wisconsinâ€“Stout)[8]\n
996   Milwaukee (Marquette University, University of...
997       Oshkosh (University of Wisconsinâ€“Oshkosh)\n
998   Platteville (University of Wisconsinâ€“Plattev...
999   River Falls (University of Wisconsinâ€“River F...
1000  Stevens Point (University of Wisconsinâ€“Steve...
1001                    Waukesha (Carroll University)\n
1002  Whitewater (University of Wisconsinâ€“Whitewat...
1003                                          Wyoming\n
1004                Laramie (University of Wyoming)[12]

[1005 rows x 1 columns]

In [56]:
#Start creating a boolean mask
estados['Flag'] = True

#Cleaning the dataframe, removing the '\n' symbol
estados['StateRegion'] = estados['StateRegion'].str.replace('\n','')

flag = []

#This function iterate the dataframe. So that if the line is the name of a state,
#True will be assigned in the list and if it is a city name, False will be assigned 
for y in df['StateRegion']:
    if y.startswith(sta):
        flag.append(True)
    else:
        flag.append(False)


df['StateFlag'] = flag
df['StateRegion'] = df['StateRegion'].str.replace('\n','')
df

                                            StateRegion  StateFlag
0                                               Alabama       True
1     Auburn (Auburn University, Edward Via College ...      False
2     Birmingham (University of Alabama at Birmingha...      False
3     Dothan (Fortis College, Troy University Dothan...      False
4                Florence (University of North Alabama)      False
5                         Homewood (Samford University)      False
6        Huntsville (University of Alabama, Huntsville)      False
7       Jacksonville (Jacksonville State University)[8]      False
8            Livingston (University of West Alabama)[8]      False
9               Mobile (University of South Alabama)[7]      False
10    Montevallo (University of Montevallo, Faulkner...      False
11    Montgomery (Alabama State University, Huntingd...      False
12                         Troy (Troy University)[8][9]      False
13    Tuscaloosa (University of Alabama, Stillman Co...      False
14                   Tuskegee (Tuskegee University)[12]      False
15                                               Alaska       True
16       Anchorage[13] (University of Alaska Anchorage)      False
17        Fairbanks (University of Alaska Fairbanks)[8]      False
18              Juneau (University of Alaska Southeast)      False
19    Ketchikan (University of Alaska Southeast-exte...      False
20    Sitka (University of Alaska Southeast-extended...      False
21                                              Arizona       True
22    Chandler[13] (Western International University...      False
23          Flagstaff (Northern Arizona University)[14]      False
24                                          Gilbert[13]      False
25    Glendale[13] (Thunderbird School of Global Man...      False
26    Lake Havasu City (ASU Colleges at Lake Havasu ...      False
27    Mesa[13] (Arizona State University Polytechnic...      False
28          Peoria[13] (Trine University branch campus)      False
29    Phoenix[13] (Arizona State University, Univers...      False
...                                                 ...        ...
975   Vancouver (Washington State University Vancouver)      False
976                                       West Virginia       True
977                      Athens (Concord University)[8]      False
978   Beckley (West Virginia University Institute of...      False
979      Buckhannon (West Virginia Wesleyan College)[8]      False
980                     Elkins (Davis & Elkins College)      False
981             Fairmont (Fairmont State University)[8]      False
982              Glenville (Glenville State College)[8]      False
983          Institute (West Virginia State University)      False
984   Lewisburg (West Virginia School of Osteopathic...      False
985            Morgantown (West Virginia University)[8]      False
986              Shepherdstown (Shepherd University)[8]      False
987           West Liberty (West Liberty University)[8]      False
988                                           Wisconsin       True
989                      Appleton (Lawrence University)      False
990   Eau Claire (University of Wisconsinâ€“Eau Claire)      False
991       Green Bay (University of Wisconsin-Green Bay)      False
992   Kenosha (University of Wisconsin-Parkside, Car...      False
993   La Crosse (University of Wisconsinâ€“La Crosse...      False
994      Madison (University of Wisconsinâ€“Madison)[8]      False
995      Menomonie (University of Wisconsinâ€“Stout)[8]      False
996   Milwaukee (Marquette University, University of...      False
997         Oshkosh (University of Wisconsinâ€“Oshkosh)      False
998   Platteville (University of Wisconsinâ€“Plattev...      False
999   River Falls (University of Wisconsinâ€“River F...      False
1000  Stevens Point (University of Wisconsinâ€“Steve...      False
1001                      Waukesha (Carroll University)      False
1002  Whitewater (University of Wisconsinâ€“Whitewat...      False
1003                                            Wyoming       True
1004                Laramie (University of Wyoming)[12]      False

[1005 rows x 2 columns]

See, now I have a boolean mask saying if the line is a state or if it's not

In [57]:
States = estados['StateRegion']
StateFlags = df['StateFlag'].values

j=0
#Here, if j=0, Bool = 'Alabama'; if j=49, Bool = 'Wyoming'
Bool = [States[j]]

#Fill in the list Bool with the name of the state while the Boolean mask is False, when it is True, 
#j gets +1 and starts to be filled with the name of the next state

for i in range(1, len(StateFlags)):
    if StateFlags[i] == True:
        j += 1
        Bool.append(States[j])
    else:
        j += 0
        Bool.append(States[j])

df['StateMatchRegion'] = Bool

df['RegionName'] = df['StateRegion'].str.replace(pat=r'\s\(.*', repl='')
df['RegionName'] = df['RegionName'].str.replace('[][13]','')
df = df.iloc[:,2:]

df.rename(columns =({'StateMatchRegion':'State'}),inplace = True)
df.drop(0, inplace = True)

In [59]:
lst = []

for x in range(0,len(df)):
    if df['State'].iloc[x] == df['RegionName'].iloc[x]:
        lst.append(x)
    else:
        continue

lst = pd.Series(lst)
a = lst + 1
a.tolist()
df = df.drop(a)
df

              State        RegionName
1           Alabama            Auburn
2           Alabama        Birmingham
3           Alabama            Dothan
4           Alabama          Florence
5           Alabama          Homewood
6           Alabama        Huntsville
7           Alabama      Jacksonville
8           Alabama        Livingston
9           Alabama            Mobile
10          Alabama        Montevallo
11          Alabama        Montgomery
12          Alabama              Troy
13          Alabama        Tuscaloosa
14          Alabama          Tuskegee
16           Alaska         Anchorage
17           Alaska         Fairbanks
18           Alaska            Juneau
19           Alaska         Ketchikan
20           Alaska             Sitka
22          Arizona          Chandler
23          Arizona         Flagstaff
24          Arizona           Gilbert
25          Arizona          Glendale
26          Arizona  Lake Havasu City
27          Arizona              Mesa
28          Arizona            Peoria
29          Arizona           Phoenix
30          Arizona          Prescott
31          Arizona        Scottsdale
32          Arizona             Tempe
...             ...               ...
972      Washington           Seattle
973      Washington           Spokane
974      Washington            Tacoma
975      Washington         Vancouver
977   West Virginia            Athens
978   West Virginia           Beckley
979   West Virginia        Buckhannon
980   West Virginia            Elkins
981   West Virginia          Fairmont
982   West Virginia         Glenville
983   West Virginia         Institute
984   West Virginia         Lewisburg
985   West Virginia        Morgantown
986   West Virginia     Shepherdstown
987   West Virginia      West Liberty
989       Wisconsin          Appleton
990       Wisconsin        Eau Claire
991       Wisconsin         Green Bay
992       Wisconsin           Kenosha
993       Wisconsin         La Crosse
994       Wisconsin           Madison
995       Wisconsin         Menomonie
996       Wisconsin         Milwaukee
997       Wisconsin           Oshkosh
998       Wisconsin       Platteville
999       Wisconsin       River Falls
1000      Wisconsin     Stevens Point
1001      Wisconsin          Waukesha
1002      Wisconsin        Whitewater
1004        Wyoming           Laramie

[955 rows x 2 columns]